// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TalepSistemi.Data;

namespace TalepSistemi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220511061540_migTalepler")]
    partial class migTalepler
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TalepSistemi.Models.Talep", b =>
                {
                    b.Property<int>("TalepID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepDepartman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TalepDurum")
                        .HasColumnType("bit");

                    b.Property<string>("TalepGonderen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TalepKonu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TalepTarih")
                        .HasColumnType("datetime2");

                    b.HasKey("TalepID");

                    b.ToTable("Talepler");
                });
#pragma warning restore 612, 618
        }
    }
}
